
const theme = {
    colors: {
      primary: "#5454d4",
      primary_light: "#6565e9",
      primary_dark: "#413e65",
      secondary: "#fedc5a",
      background_primary: "#ffffff",
      background_secondary: "#e0dedc",
      title: "#19191b",
      text: "#222222",
      element_base: "#f7f7fb",
      success: "#77bf41",
      alert: "#d97934",
      error: "#d9344f",
      white: "#ffffff",
      silver: "#C0C0C0",
      black: "#000000",
    },
    fonts: {
      default: "Poppins",
      secondary: "Montserrat",
    },
    sizes: {
      xxsmall: ".64rem",
      xsmall: ".72rem",
      small: ".8rem",
      normal: ".88rem",
      medium: "1rem",
      large: "1.2rem",
      xlarge: "1.6rem",
      xxlarge: "2rem",
      huge: "2.4rem",
      xhuge: "3.2rem",
      xxhuge: "4rem",
      hero: "4.4rem",
      xhero: "4.8rem",
      xxhero: "5.2rem",
    },
    spacings: {
      xxtiny: "0.16rem",
      xtiny: "0.24rem",
      tiny: "0.4rem",
      xxsmall: "0.8rem",
      xsmall: "1.2rem",
      small: "1.6rem",
      mediumSmall: "2.0rem",
      medium: "2.4rem",
      mediumLarge: "2.8rem",
      large: "3.2rem",
      xlarge: "3.6rem",
      xxlarge: "4.0rem",
      huge: "4.4rem",
      xhuge: "4.8rem",
      xxhuge: "5.6rem",
      hero: "6.4rem",
      xhero: "7.2rem",
      xxhero: "8.0rem",
    },
    transitions: {
      fastest: "all 100ms ease-in-out",
      faster: "all 200ms ease-in-out",
      fast: "all 300ms ease-in-out",
      normal: "all 500ms ease-in-out",
      slow: "all 600ms ease-in-out",
      slower: "all 800ms ease-in-out",
      slowest: "all 1s ease-in-out",
    },
    shadows: {
      soft: "rgba(10, 10, 10, 0.1) 0px 8px 16px -2px, rgba(10, 10, 10, 0.02) 0px 0px 0px 1px;",
    },
  };
  
  export { theme };